// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbjvuocvmvatsqpoaqsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhianZ1b2N2bXZhdHNxcG9hcXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0ODI5MzIsImV4cCI6MjA1ODA1ODkzMn0.dYB0XJE7dB2kTNJTMooc6ZfN-T2wNw0EmvLzK94_Xug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);